### ISSUE TITLE
Wrong service name "mysqld" in vagrant/bootstrap.sh

### ISSUE THREAD

**Issue by yoku0825** [box/Anemometer#133]
There's a mistype in bootstrap.sh.

$ vagrant up
..
==> default: error reading information on service mysqld: No such file or directory
..

"chkconfig --levels 235 mysqld on" have to be "chkconfig --levels 235 mysql on"

**Comment by akuzminsky** [comment]
We moved vagrant VM provisioning to puppet where this bug is already fixed
