### ISSUE TITLE
Blank page after selecting a Datasource

### ISSUE THREAD

**Issue by agougousis** [box/Anemometer#182]
Hi! I have installed Anemometer following all the steps described in Anemometer's page but after sel;ecting the data source (in the home page) I get a blank page with no errors. The slow_query_log database has been filled with data.

Any ideas?

**Comment by tkarraker** [comment]
@agougousis This sounds like a suppressed php error. Database connection failure is the most likely, but due to the database being populated, it may not be. Is there anything in your web server's error log related to anemometer?

**Comment by agougousis** [comment]
Yeap!

PHP Fatal error:  Uncaught exception 'Exception' with message 'Access denied for user 'root'@'localhost' (using password: NO)' in /var/www/anemometer/lib/AnemometerModel.php:282\nStack trace:\n#0 /var/www/anemometer/lib/Anemometer.php(64): AnemometerModel->connect_to_datasource()\n#1 /var/www/anemometer/index.php(37): Anemometer->__construct(Array)\n#2 {main}\n  thrown in /var/www/anemometer/lib/AnemometerModel.php on line 282, referer: http://box-anemometer.gr/index.php

But why it is trying to connect with "root@localhost"?  I have configured user and password in both $conf['datasources']['localhost']  and  $conf['plugins']...'explain' and neither is root.

**Comment by tkarraker** [comment]
I wonder if we're seeing problems with the merge to include multiple config files. How do you have the config files set up in conf/? I'm thinking you copied the sample config to config.inc.php, included your data and still have datasource_localhost.inc.php from the initial pull. If this is the case, try deleting that file if it exists. If this does not fix the issue, can you show me a copy of the conf/ file structure and any config files you have with passwords removed?

**Comment by agougousis** [comment]
I deleted datasource_localhost.inc.php and now it works fine! Thanks!
By the way, is there any place I can find the definition for each query metric produced by --history ?

**Comment by tkarraker** [comment]
I'm going to close out this issue as the primary issue is resolved. Regarding metrics definitions, we do not have any documentation on it presently. However, it's something we would highly consider a pull request for in the future.
