### ISSUE TITLE
Maintaining of Anemometer

### ISSUE THREAD

**Issue by nizsheanez** [box/Anemometer#190]
Hi, as i see last commit was in October 2016, but our company Lazada.com would like to do some improvements and maintain the project. 

What way do you suggest to us? Make our fork or some other way?

**Comment by akuzminsky** [comment]
Hi,

Send us a PR and please make sure you have unit test for your changes.

See mode details in 
https://github.com/box/Anemometer/blob/develop/CONTRIBUTING.md

**Comment by nizsheanez** [comment]
Ok, thanks.
