### ISSUE TITLE
Using ts_min instead of ts_max

### ISSUE THREAD

**Issue by deviantdolphin** [box/Anemometer#27]
Hi,
First thank you for making this public.  This interface is really good.

I am having a problem where slow queries do not show up on interface no matter how i search.
However i can pull them up if i look in database find the checksums and then enter those in the interface.

I think the problem is that queries use ts_min instead of ts_max in the where clause.

I believe ts_max makes more sense because ts_max represents the last time a query ran slow.

When i switch ts_min to ts_max and run query manually i see the results I want however, I cannot find where to make this change in your code.  Could you please advise me on how i can make this change so i can experiment? 

Thanks
-Eric

SELECT hostname_max AS `hostname_max`,
  checksum AS `checksum`,
  LEFT(dimension.sample,80) AS `snippet`,
  ROUND(SUM(Rows_examined_sum)/SUM(rows_sent_sum),2) AS `index_ratio`,
  SUM(Query_time_sum) / SUM(ts_cnt) AS `query_time_avg`,
  ROUND(SUM(Rows_sent_sum)/SUM(ts_cnt),0) AS `rows_sent_avg`,
  SUM(ts_cnt) AS `ts_cnt`,
  SUM(Query_time_sum) AS `Query_time_sum`,
  SUM(Lock_time_sum) AS `Lock_time_sum`,
  SUM(Rows_sent_sum) AS `Rows_sent_sum`,
  SUM(Rows_examined_sum) AS `Rows_examined_sum`,
  SUM(Full_scan_sum) AS `Full_scan_sum`,
  SUM(Tmp_table_sum) AS `Tmp_table_sum`,
  SUM(Filesort_sum) AS `Filesort_sum`
 FROM `global_query_review` AS `fact` 
 JOIN `global_query_review_history` AS `dimension` USING (`checksum`) 
 WHERE hostname_max = "sanitized"
  AND dimension.ts_min >= "2012-06-07 04:55:27"
  AND dimension.ts_min <= "2012-06-07 08:55:27"
 GROUP BY checksum 
 ORDER BY Query_time_sum DESC 
 LIMIT 20

**Comment by AlienFromStar** [comment]
thank your update, 
'special_field_names' => array(
    'time'      => 'ts_max',
)

this may dosn't work for mysql 5.7, how i can do?
