### ISSUE TITLE
Importing the $event->{user} and $event->{host} into global_query_review_history

### ISSUE THREAD

**Issue by robayer** [box/Anemometer#71]
It would be extremely helpful to be able to import these values for each entry if possible. I can see that pt_query_digest has this information but can it printed on a per-query basis inserted into the database?

**Comment by mhoareau84** [comment]
Thanks a lot for this tip!
In my case, it is very useful to have the user for each entry as I have several applications using the same db with different mysql users.
I spent some time to figure how can I achieve this... Then I found this issue.
Very glad to see that this can be simply done.

I think it will be very useful to have it in the default sql installation script or in the documentation.
